steps:

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/gke-demo-app:$SHORT_SHA .']
   secretEnv: ['USERNAME']

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/gke-demo-app:$SHORT_SHA']
   secretEnv: ['USERNAME']

 - name: 'omegaes/kubci'
   args: ['$SHORT_SHA']
   secretEnv: ['ENV_REPO_URL']
   env:
    - 'ENV_REPO_FILES=$_ENV_REPO_FILES'
    - 'ENV_REPO_MERGE_BRANCH=$_ENV_REPO_MERGE_BRANCH'
    - 'ENV_REPO_TARGET_BRANCH=$_ENV_REPO_TARGET_BRANCH'
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'

availableSecrets:
    secretManager:
    - versionName: projects/150435548913/secrets/DOCKER_PASSWORD_SECRET_NAME/versions/1
      env: 'PASSWORD'
    - versionName: projects/150435548913/secrets/DOCKER_USERNAME_SECRET_NAME/versions/3
      env: 'USERNAME'
    - versionName: projects/150435548913/secrets/ENV_REPO_AUTH_URL/versions/1
      env: 'ENV_REPO_URL'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 720s
tags: ['masterBuild', 'ApiV3Build']
