steps:

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['build', 'gcr.io/${_PROJECT}:$SHORT_SHA','.']

 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['push','gcr.io/${_PROJECT}:$SHORT_SHA']

 - name: 'omegaes/kubci'
   args: ['$SHORT_SHA']
   secretEnv: ['ENV_REPO_URL']
   env:
    - 'ENV_REPO_FILES=$_ENV_REPO_FILES'
    - 'ENV_REPO_MERGE_BRANCH=$_ENV_REPO_MERGE_BRANCH'
    - 'ENV_REPO_TARGET_BRANCH=$_ENV_REPO_TARGET_BRANCH'
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'

substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: argocd-352710
    _ZONE: us-central1-a 

availableSecrets:
    secretManager:
    - versionName: projects/150435548913/secrets/ENV_REPO_AUTH_URL/versions/1
      env: 'ENV_REPO_URL'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 720s
tags: ['masterBuild', 'ApiV3Build']
