version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gke-demo-app
    ports:
      - 7000:8080
    volumes:
      - ./src:/usr/src/app
      - ./package.json:/usr/src/package.json